---
- name: build ami
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: create log directory
      file:
        path: /var/log/applog
        state: directory
        mode: 0755
      become: yes
